// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CloneEbayDbContext))]
    [Migration("20260724191551_AddCartAndPayPalFields")]
    partial class AddCartAndPayPalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("country");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullName");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("isDefault");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("street");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Address__3213E83F58794D6D");

                    b.HasIndex(new[] { "UserId" }, "IX_Address_userId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("BidTime")
                        .HasColumnType("datetime")
                        .HasColumnName("bidTime");

                    b.Property<int?>("BidderId")
                        .HasColumnType("int")
                        .HasColumnName("bidderId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.HasKey("Id")
                        .HasName("PK__Bid__3213E83F51E40AD4");

                    b.HasIndex(new[] { "BidderId" }, "IX_Bid_bidderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_Bid_productId");

                    b.ToTable("Bid", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3213E83F");

                    b.HasIndex(new[] { "UserId" }, "IX_Cart_userId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Backend.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("addedAt");

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cartId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3213E83F");

                    b.HasIndex(new[] { "CartId" }, "IX_CartItem_cartId");

                    b.HasIndex(new[] { "ProductId" }, "IX_CartItem_productId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Category__3213E83FFBFAA45E");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discountPercent");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("endDate");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("int")
                        .HasColumnName("maxUsage");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("startDate");

                    b.Property<int?>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("usedCount");

                    b.HasKey("Id")
                        .HasName("PK__Coupon__3213E83F5322616E");

                    b.HasIndex(new[] { "ProductId" }, "IX_Coupon_productId");

                    b.ToTable("Coupon", (string)null);
                });

            modelBuilder.Entity("Backend.Models.DetailFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Communication")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryOnTime")
                        .HasColumnType("int");

                    b.Property<int?>("ExactSame")
                        .HasColumnType("int");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("feedbackId");

                    b.HasKey("Id")
                        .HasName("PK__DetailFe__3213E83F0A7DCC61");

                    b.HasIndex("FeedbackId");

                    b.ToTable("DetailFeedback", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Dispute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("RaisedBy")
                        .HasColumnType("int")
                        .HasColumnName("raisedBy");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("SolvedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("solvedDate");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("submittedDate");

                    b.HasKey("Id")
                        .HasName("PK__Dispute__3213E83FC7A98713");

                    b.HasIndex(new[] { "OrderId" }, "IX_Dispute_orderId");

                    b.HasIndex(new[] { "RaisedBy" }, "IX_Dispute_raisedBy");

                    b.ToTable("Dispute", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("averageRating");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PositiveRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("positiveRate");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.Property<int?>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("totalReviews");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3213E83F7404CC3B");

                    b.HasIndex(new[] { "OrdersId" }, "IX_Feedback_OrdersId");

                    b.HasIndex(new[] { "SellerId" }, "IX_Feedback_sellerId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("lastUpdated");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__Inventor__3213E83F48B36DEB");

                    b.HasIndex(new[] { "ProductId" }, "IX_Inventory_productId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("content");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiverId");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("senderId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("Backend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("unitPrice");

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3213E83F7EC2808B");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderItem_orderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderItem_productId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Backend.Models.OrderTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("addressId");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("buyerId");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("couponId");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("discountAmount");

                    b.Property<bool?>("IsCommented")
                        .HasColumnType("bit")
                        .HasColumnName("isCommented");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderDate");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("shippingFee");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("subTotal");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totalPrice");

                    b.HasKey("Id")
                        .HasName("PK__OrderTab__3213E83F282EE92F");

                    b.HasIndex("CouponId");

                    b.HasIndex(new[] { "AddressId" }, "IX_OrderTable_addressId");

                    b.HasIndex(new[] { "BuyerId" }, "IX_OrderTable_buyerId");

                    b.ToTable("OrderTable", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("method");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime")
                        .HasColumnName("paidAt");

                    b.Property<string>("PayPalCaptureId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paypalCaptureId");

                    b.Property<string>("PayPalOrderId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paypalOrderId");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3213E83FC485D7F6");

                    b.HasIndex(new[] { "OrderId" }, "IX_Payment_orderId");

                    b.HasIndex(new[] { "UserId" }, "IX_Payment_userId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ProcessedWebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.ToTable("ProcessedWebhookEvent", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuctionEndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("auctionEndTime");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("images");

                    b.Property<bool?>("IsAuction")
                        .HasColumnType("bit")
                        .HasColumnName("isAuction");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Product__3213E83FEFD48A5F");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Product_categoryId");

                    b.HasIndex(new[] { "SellerId" }, "IX_Product_sellerId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK__ReturnRe__3213E83FC9454B62");

                    b.HasIndex(new[] { "OrderId" }, "IX_ReturnRequest_orderId");

                    b.HasIndex(new[] { "UserId" }, "IX_ReturnRequest_userId");

                    b.ToTable("ReturnRequest", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("reviewerId");

                    b.HasKey("Id")
                        .HasName("PK__Review__3213E83F0BF301EC");

                    b.HasIndex(new[] { "ProductId" }, "IX_Review_productId");

                    b.HasIndex(new[] { "ReviewerId" }, "IX_Review_reviewerId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Backend.Models.SellerToBuyerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__SellerTo__3214EC079F3BB7E7");

                    b.ToTable("SellerToBuyerReview", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ShippingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("carrier");

                    b.Property<DateTime?>("EstimatedArrival")
                        .HasColumnType("datetime")
                        .HasColumnName("estimatedArrival");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trackingNumber");

                    b.HasKey("Id")
                        .HasName("PK__Shipping__3213E83FF99F0D65");

                    b.HasIndex(new[] { "OrderId" }, "IX_ShippingInfo_orderId");

                    b.ToTable("ShippingInfo", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bannerImageURL");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("sellerId");

                    b.Property<string>("StoreName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("storeName");

                    b.HasKey("Id")
                        .HasName("PK__Store__3213E83FF102737C");

                    b.HasIndex(new[] { "SellerId" }, "IX_Store_sellerId");

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatarURL");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F0238F3F7");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E6164741FE703")
                        .IsUnique()
                        .HasFilter("([email] IS NOT NULL)");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Address__userId__3A81B327");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Bid", b =>
                {
                    b.HasOne("Backend.Models.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .HasConstraintName("FK__Bid__bidderId__5629CD9C");

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Bids")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Bid__productId__5535A963");

                    b.Navigation("Bidder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Cart__userId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.CartItem", b =>
                {
                    b.HasOne("Backend.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__cartId");

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CartItem__productId");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Coupon", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Coupons")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Coupon__productI__60A75C0F");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.DetailFeedback", b =>
                {
                    b.HasOne("Backend.Models.Feedback", "Feedback")
                        .WithMany("DetailFeedbacks")
                        .HasForeignKey("FeedbackId")
                        .IsRequired()
                        .HasConstraintName("FK_DetailFeedback_Feedback");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("Backend.Models.Dispute", b =>
                {
                    b.HasOne("Backend.Models.OrderTable", "Order")
                        .WithMany("Disputes")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Dispute__orderId__693CA210");

                    b.HasOne("Backend.Models.User", "RaisedByNavigation")
                        .WithMany("Disputes")
                        .HasForeignKey("RaisedBy")
                        .HasConstraintName("FK__Dispute__raisedB__6A30C649");

                    b.Navigation("Order");

                    b.Navigation("RaisedByNavigation");
                });

            modelBuilder.Entity("Backend.Models.Feedback", b =>
                {
                    b.HasOne("Backend.Models.OrderTable", "Orders")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrdersId");

                    b.HasOne("Backend.Models.User", "Seller")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK__Feedback__seller__66603565");

                    b.Navigation("Orders");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend.Models.Inventory", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Inventory__produ__6383C8BA");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Message", b =>
                {
                    b.HasOne("Backend.Models.Product", null)
                        .WithMany("Messages")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Backend.Models.OrderItem", b =>
                {
                    b.HasOne("Backend.Models.OrderTable", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderItem__order__46E78A0C");

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__OrderItem__produ__47DBAE45");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.OrderTable", b =>
                {
                    b.HasOne("Backend.Models.Address", "Address")
                        .WithMany("OrderTables")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__OrderTabl__addre__440B1D61");

                    b.HasOne("Backend.Models.User", "Buyer")
                        .WithMany("OrderTables")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK__OrderTabl__buyer__4316F928");

                    b.HasOne("Backend.Models.Coupon", "Coupon")
                        .WithMany("OrderTables")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK_OrderTable_couponId");

                    b.Navigation("Address");

                    b.Navigation("Buyer");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Backend.Models.Payment", b =>
                {
                    b.HasOne("Backend.Models.OrderTable", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Payment__orderId__4AB81AF0");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Payment__userId__4BAC3F29");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Product__categor__3F466844");

                    b.HasOne("Backend.Models.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK__Product__sellerI__403A8C7D");

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend.Models.ReturnRequest", b =>
                {
                    b.HasOne("Backend.Models.OrderTable", "Order")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__ReturnReq__order__5165187F");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ReturnReq__userI__52593CB8");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Review", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Review__productI__59063A47");

                    b.HasOne("Backend.Models.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FK__Review__reviewer__59FA5E80");

                    b.Navigation("Product");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Backend.Models.ShippingInfo", b =>
                {
                    b.HasOne("Backend.Models.OrderTable", "Order")
                        .WithMany("ShippingInfos")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__ShippingI__order__4E88ABD4");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Backend.Models.Store", b =>
                {
                    b.HasOne("Backend.Models.User", "Seller")
                        .WithMany("Stores")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK__Store__sellerId__6D0D32F4");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend.Models.Address", b =>
                {
                    b.Navigation("OrderTables");
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Coupon", b =>
                {
                    b.Navigation("OrderTables");
                });

            modelBuilder.Entity("Backend.Models.Feedback", b =>
                {
                    b.Navigation("DetailFeedbacks");
                });

            modelBuilder.Entity("Backend.Models.OrderTable", b =>
                {
                    b.Navigation("Disputes");

                    b.Navigation("Feedbacks");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("ReturnRequests");

                    b.Navigation("ShippingInfos");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("CartItems");

                    b.Navigation("Coupons");

                    b.Navigation("Inventories");

                    b.Navigation("Messages");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Bids");

                    b.Navigation("Carts");

                    b.Navigation("Disputes");

                    b.Navigation("Feedbacks");

                    b.Navigation("OrderTables");

                    b.Navigation("Payments");

                    b.Navigation("Products");

                    b.Navigation("ReturnRequests");

                    b.Navigation("Reviews");

                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
